### ISSUE TITLE
Hero sprite open source conversion issue

### ISSUE THREAD

**Issue by Bertram25** [solarus-games/children-of-solarus#4]
@christopho 

This issue is about converting the hero sprite.

As those files are the most important ones, the ones the player sees all the time, I made a separate issue se we can have an extra care about that part.

Very first thing to set up: One must come with an acceptable concept of base sprite that will be used as a reference for the replacement.

**Comment by christopho** [comment]
@Bertram25 any chance you can work on the sword animations? I think this is the main showstopper right now.

**Comment by Bertram25** [comment]
@christopho I cannot promise anything atm. But it's duly noted.
Btw, this project needs a true leader. Something I cannot do atm. Is there a developer interested?
I can help with art from time to time. :)

**Comment by christopho** [comment]
Ok thanks for the reply @Bertram25!
I want to work more on this project, even if I am already working on several games. Because gathering free resources for this one is very useful for the sample quest and to ultimately obtain a free resource pack.
And yes, I am definitely interested if you can find time to make pixel art sometimes because I am not very good at it!

**Comment by oclero** [comment]
Hi everyone.
For the new version of the Solarus website, I plan to imagine and draw characters who will be GPL (a hero, a princess, an evil guy) to illustrate the website without using Zelda characters. Maybe the sprite could be inspired from my drawings. The hero wil look a lot like an old character I did: http://oclero.deviantart.com/art/Heros-chevauchant-un-cerf-380074615
What do you think ?

**Comment by christopho** [comment]
He is very nice for sure! I don't know who could make a sprite from it for now.

**Comment by Diarandor** [comment]
Fortunately, this issue will be closed soon, since I am re-licensing all my art into CC-BY-SA, which is free. That includes almost all the hero animations, and the remaining ones (some shields, and variants with different colors of each weapon and tunic) will be finished soon.

**Comment by Diarandor** [comment]
I was thinking that since the hero I made has red hair and the tunic is big, it will be annoying to use a red tunic (as the third tunic) since there would be too much red. 

Maybe an option is to say that the tunics are magic and change also all the colors of the hero, including the hair color (so we would have better color contrasts). Do you agree?

An example of this idea was used for all the 6 heroes in the game Seiken Densetsu 3 (when you level up, all colors change), for instance: http://home.arcor.de/minako.aino/sd3/duran/duran-classes-neu.png

**Comment by christopho** [comment]
Or the third tunic can have another color, we don't really care in this particular game.

**Comment by Diarandor** [comment]
Ok. I will use a different color for the gabardine tunic.

**Comment by oclero** [comment]
Yes, it is not an obligation to have the same tunic colors as in Zelda games.

**Comment by Diarandor** [comment]
I think I will make a blue/silver-plated tunic and a yellow/golden tunic. If they do not look good we can change again later.

**Comment by Diarandor** [comment]
This is the current state of the free hero animations:
https://github.com/Diarandor/repository/issues/12

Everything is CC-BY-SA, and can be found too here:
http://diarandor.deviantart.com

**Comment by christopho** [comment]
"@christopho I cannot promise anything atm. But it's duly noted.
Btw, this project needs a true leader. Something I cannot do atm. Is there a developer interested?
I can help with art from time to time. :)"

@Bertram25 Are you still looking for someone to manage the Children of Solarus project? This is becoming a priority for the the team now that Solarus 1.5 is out. We will work a lot on it with @Diarandor, he is making tremendous progress with a lot of nice free graphics and sounds right now. If you still don't have a lot of time, I can continue the task. Can you transfer the ownership of the repository to me then? You will still be able to contribute with art of course. Thanks!

**Comment by oclero** [comment]
@christopho Why not giving ownership of ChildrenOfSolarus to **solarus-games** organization (https://github.com/solarus-games) ? (just a proposition)

**Comment by christopho** [comment]
Maybe, I don't know much about organizations :)

**Comment by oclero** [comment]
It's not really different from a user's github account, Github themselves explain better what you can do: https://github.com/blog/674-introducing-organizations
It is rather trendy nowadays for open-source projects to have their repositories in an organization account. @christopho you are already owner/administrator of the organization.

**Comment by christopho** [comment]
@oclero @Bertram25 Ok to transfer it to the solarus-games organization then. I will do the same for all our projects as well.

**Comment by Bertram25** [comment]
@christopho Yep, I'm dying to see something out of this project so I giving it to you gladly. :)

Have fun!

**Comment by Diarandor** [comment]
I am now working on the tilesets. Although I am a bit slow, I think I can finish all the tilesets before June 2017, or at least that is my intention. The two overworld tilesets (and maybe some more) may be finished before December.

**Comment by christopho** [comment]
Thanks @Bertram25! We will do our best!

**Comment by Diarandor** [comment]
At present, I think that only the running and super-spin attack animations are missing for Eldran. The rest are just color variants or shape variants of the weapon. Since the shield is planned to be used like in LA, most shield animations are unnecessary.

**Comment by Diarandor** [comment]
Running animations are now done (with and without sword). The unchecked animations above are not necessary since we will use the custom shield.
1. The superspin attack animation is still missing, but I will open a new issue for that one. We may use a different animated attack instead. And in case we use the same one, it can be done with a loop on the normal "spin" animation.
2. I will open another issue for the tunic variants (color variants).
